apiVersion: v1
kind: Pod
metadata:
  namespace: jgreben
  name: okapi-init-pod
  labels:
    app: okapi-db
spec:
  containers:
  - name: okapi-init
    image: jgreben/postgres:latest
    resources:
      requests:
        memory: "75M"
        cpu: ".01"
      limits:
        memory: "250M"
        cpu: ".02"
    env:
    - name: PG_DB_HOST
      value: "folio-jgreben-okapi-rds.clqwjadk8neo.us-west-2.rds.amazonaws.com"
    #use POSTGRES_PASSWORD to ssh into the pod
    - name: POSTGRES_PASSWORD
      value: 'password'
    #use PGPASSWORD when running the init script
#    - name: PGPASSWORD
#      value: 'EfAdCymKecZov'
#   Optionally run a command
#    command: ["sh", "-c", "
#      psql -U okapi -h $(PG_DB_HOST) -w -c \"DROP DATABASE IF EXISTS okapi;\"
#    "]
